# OER Attribution

## Chapter 1

|  |  |
|:-----------------------------------|:-----------------------------------|
| Parts of the Introduction | ["African Virtual University"](http://oer.avu.org/bitstream/handle/123456789/72/Developmental%20Psychology.pdf?sequence=1 "http://oer.avu.org/bitstream/handle/123456789/72/Developmental%20Psychology.pdf?sequence=1") by John T. Phiri is licensed under [CC BY 2.5](http://creativecommons.org/licenses/by/2.5 "http://creativecommons.org/licenses/by/2.5") |
| Throughout Chapter | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Parts of Theorists and Research Methods | ["Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]"](http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf "http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf") by Martha Lally and Suzanne Valentine-French is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") / A derivative from the original work |

## Chapter 2

|  |  |
|:-----------------------------------|:-----------------------------------|
| Throughout Chapter | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |

## Chapter 3

|  |  |
|:-----------------------------------|:-----------------------------------|
| Throughout Chapter | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Parts of Language Section | ["Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]"](http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf "http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf") by Martha Lally and Suzanne Valentine-French is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") / A derivative from the original work |
| Parts of Parenting | ["The Developing Parent"](http://nobaproject.com/modules/the-developing-parent "http://nobaproject.com/modules/the-developing-parent") by NOBA is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |

## Chapter 4

|  |  |
|:-----------------------------------|:-----------------------------------|
| Throughout Chapter | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Theory of Mind | ["Theory of Mind"](http://nobaproject.com/modules/theory-of-mind "http://nobaproject.com/modules/theory-of-mind") by NOBA is licensed under [CC BY 4.0](http://creativecommons.org/licenses/by/4.0 "http://creativecommons.org/licenses/by/4.0") |

## Chapter 5

|  |  |
|:-----------------------------------|:-----------------------------------|
| Throughout Chapter | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Education Topics | ["Educational Psychology"](http://cnx.org/contents/ce6c5eb6-84d3-4265-9554-84059b75221e@2.1. "http://cnx.org/contents/ce6c5eb6-84d3-4265-9554-84059b75221e@2.1.") by Kelvin Seifert is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Intelligence and Moral Development | ["Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]"](http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf "http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf") by Martha Lally and Suzanne Valentine-French is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") / A derivative from the original work |

## Chapter 6

|  |  |
|:-----------------------------------|:-----------------------------------|
| Peers and Romantic Relationships | ["Adolescent Development"](http://nobaproject.com/modules/adolescent-development "http://nobaproject.com/modules/adolescent-development") by NOBA is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |

## Chapter 7

|  |  |
|:-----------------------------------|:-----------------------------------|
| Sexual Responsiveness Peak, Friendships, Love, and Tacit Knowledge | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Parenthood | ["The Developing Parent"](http://nobaproject.com/modules/the-developing-parent "http://nobaproject.com/modules/the-developing-parent") by NOBA is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |

## Chapter 8

|  |  |
|:-----------------------------------|:-----------------------------------|
| Mechanics of Cognition, Aspects of Midlife Crisis, and Aspects of Family Relationships | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Intelligence | ["Introduction to Psychology \[Adapted from Charles Stangor, Introduction to Psychology\]"](http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf "http://dept.clcillinois.edu/psy/IntroductionToPsychologyText.pdf") by Martha Lally and Suzanne Valentine-French is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") / A derivative from the original work |
| Aspects of Physical Aging | ["Psychology"](https://www.boundless.com/psychology/textbooks/boundless-psychology-textbook/human-development-14/early-and-middle-adulthood-74/physical-development-in-adulthood-287-12822/ "https://www.boundless.com/psychology/textbooks/boundless-psychology-textbook/human-development-14/early-and-middle-adulthood-74/physical-development-in-adulthood-287-12822/") by Boundless is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Stress | ["The Healthy Life"](http://nobaproject.com/modules/the-healthy-life "http://nobaproject.com/modules/the-healthy-life") by NOBA is licensed under [CC BY-SA 3.0](http://creativecommons.org/licenses/by-sa/3.0 "http://creativecommons.org/licenses/by-sa/3.0") |
| Friendship | ["Love, Friendship and Social Support"](http://nobaproject.com/modules/love-friendship-and-social-support "http://nobaproject.com/modules/love-friendship-and-social-support") by NOBA is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |

## Chapter 9

|  |  |
|:-----------------------------------|:-----------------------------------|
| Aspects of Aging | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |
| Successful Aging and Social Networks | ["Aging"](http://nobaproject.com/modules/aging "http://nobaproject.com/modules/aging") by NOBA is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |

## Chapter 10

|  |  |
|:-----------------------------------|:-----------------------------------|
| Aspects of Death, Kübler-Ross Model, and Anticipatory Grief | ["Psyc 200 Lifespan Psychology"](http://opencourselibrary.org/econ-201/ "http://opencourselibrary.org/econ-201/") by Laura Overstreet is licensed under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0 "http://creativecommons.org/licenses/by/3.0") |